CREATE TABLE `books` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` char(100) CHARACTER SET utf8 NOT NULL,
  `link` char(100) CHARACTER SET utf8 NOT NULL,
  `content` longtext CHARACTER SET utf8 NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8;

INSERT INTO `books` VALUES (1, 'The Inevitable', 'the-inevitable', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim.\r\n\r\nDonec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus.\r\n\r\nAenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi.\r\n\r\nNam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc,');
INSERT INTO `books` VALUES (2, 'PHP For Dummies', 'php-for-dummies', 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.\r\n\r\nNemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.\r\n\r\nUt enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?\r\n\r\nAt vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere');
INSERT INTO `books` VALUES (3, 'Back To The Future', 'back-to-the-future', 'Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. A small river named Duden flows by their place and supplies it with the necessary regelialia.\r\n\r\nIt is a paradisematic country, in which roasted parts of sentences fly into your mouth. Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life One day however a small line of blind text by the name of Lorem Ipsum decided to leave for the far World of Grammar.\r\n\r\nThe Big Oxmox advised her not to do so, because there were thousands of bad Commas, wild Question Marks and devious Semikoli, but the Little Blind Text didn’t listen. She packed her seven versalia, put her initial into the belt and made herself on the way. When she reached the first hills of the Italic Mountains, she had a last view back on the skyline of her hometown Bookmarksgrove, the headline of Alphabet Village and the subline of her own road, the Line Lane. Pityful a rethoric question ran over her cheek, then');
INSERT INTO `books` VALUES (4, 'Watch Shop Bible', 'watch-shop-bible', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam sodales, augue sit amet mattis eleifend, tellus quam vestibulum ipsum, et vestibulum felis tellus at velit. Pellentesque at quam lorem. Vivamus sit amet iaculis urna. Sed lectus neque, tristique nec volutpat id, elementum eget dui. Etiam scelerisque nulla ut feugiat interdum. Mauris non rhoncus tellus. Quisque in porta magna. In sed efficitur nibh. Phasellus imperdiet lacus sed nulla consectetur, ac interdum arcu pellentesque. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nunc pulvinar pellentesque convallis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nam eget feugiat dolor. Vivamus hendrerit feugiat sapien vulputate hendrerit. Pellentesque pretium condimentum dolor, in dignissim erat accumsan at.\r\n\r\nCras lacinia leo at tortor feugiat tincidunt. Sed fringilla velit at diam facilisis, sit amet bibendum justo faucibus. Maecenas lobortis a nibh rhoncus luctus. Maecenas eu magna lobortis, bibendum lectus a, sagittis tellus. Pellentesque eu erat feugiat, cursus diam id, bibendum libero. Aenean vehicula eget turpis sed venenatis. In dapibus sapien ac pellentesque hendrerit. Duis quam erat, molestie molestie venenatis eu, sollicitudin id felis. Nulla ut tellus ac erat tincidunt consequat eget id nisi.\r\n\r\nPraesent non massa at erat ornare interdum. Nullam quis nibh eget dolor bibendum molestie a eu est. Integer ornare nec urna sed efficitur. Nunc viverra lacus ac ultricies lobortis. Integer aliquet euismod augue ac ultrices. Phasellus a lacus nisi. Suspendisse aliquet lectus ut libero blandit bibendum. Ut vulputate posuere eros, non luctus massa volutpat nec.\r\n\r\nDonec id quam accumsan, tincidunt arcu a, tristique purus. Aliquam in sem ac mauris iaculis condimentum. Donec sit amet metus justo. Ut semper pellentesque lacus, fringilla molestie sem tincidunt id. Vivamus tristique ante vitae nibh sagittis, sit amet imperdiet felis dapibus. Fusce in ligula non libero ultricies tincidunt. Donec venenatis dignissim fermentum. Aliquam non lacus tincidunt justo consectetur pellentesque.\r\n\r\nEtiam viverra placerat enim a venenatis. Nam id malesuada orci. Cras imperdiet non odio non ullamcorper. Aliquam sollicitudin, augue et mollis lacinia, eros lectus porta dolor, ac tincidunt est neque a leo. Praesent vehicula nec velit nec dapibus. Mauris metus orci, maximus quis viverra ut, congue sed sem. Aliquam erat volutpat. Nam tincidunt condimentum malesuada.');
INSERT INTO `books` VALUES (5, 'History Mode', 'history-mode', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In augue ante, blandit nec dignissim sed, tincidunt vitae augue. Nulla scelerisque dictum vehicula. Donec id scelerisque orci. Quisque finibus turpis in molestie faucibus. Ut fermentum lobortis sem ac pellentesque. Aenean nec odio non nibh consectetur iaculis. Donec iaculis venenatis diam a maximus. Aenean ante leo, iaculis id hendrerit sed, gravida vel turpis. Nullam facilisis felis diam, in tempor metus semper vel. Phasellus vulputate turpis non diam bibendum porta. Praesent iaculis eget diam ac fermentum. Donec vulputate elit et lacinia suscipit.\r\n\r\nCurabitur id sollicitudin sem. Nullam a fringilla ligula, at finibus risus. Sed auctor neque tincidunt dui pulvinar placerat. Integer sit amet risus mollis, pulvinar lectus viverra, vestibulum dui. Fusce scelerisque bibendum felis, eget fringilla metus condimentum ac. Pellentesque vitae congue risus. Phasellus dictum quam urna. Ut gravida nunc ut suscipit condimentum. Etiam non lorem a velit vestibulum cursus.\r\n\r\nMauris pretium pharetra justo ac tempor. Donec viverra magna a pellentesque luctus. Nullam quis enim id lacus tristique mattis. Nulla non ipsum interdum, faucibus quam et, ultricies felis. Fusce sed mollis justo. Mauris quis elementum mauris. Duis et dignissim libero. In hac habitasse platea dictumst. Fusce mattis fringilla orci, sed feugiat dui suscipit id. Donec nec eleifend risus. Donec ligula erat, luctus id ipsum a, sollicitudin porttitor ligula.\r\n\r\nNunc quis gravida ligula, faucibus pellentesque dui. Nunc purus eros, laoreet id mauris eget, luctus venenatis ante. In in blandit est. Curabitur et odio eu tortor efficitur eleifend. Quisque eu turpis sit amet metus ullamcorper dignissim non ut elit. Phasellus aliquam eros sodales massa tincidunt, sit amet malesuada mi varius. Vestibulum et felis sed lorem tempus dignissim quis nec ante. Aliquam suscipit enim in ipsum volutpat tempus. Nulla ac mattis ex.');
INSERT INTO `books` VALUES (6, 'Flash Forward', 'flash-forward', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac purus eu lorem varius suscipit tristique quis diam. Vestibulum blandit lacus et nisl efficitur, ornare consectetur magna maximus. Proin ac felis ornare, suscipit tellus sed, accumsan nibh. Proin malesuada id turpis et tempus. Ut eu porttitor nulla. Duis metus purus, cursus in lacus eget, tincidunt iaculis justo. Nullam vestibulum turpis eget nulla sodales, et auctor tortor maximus. Mauris eu mauris risus. Mauris eu sodales eros, consectetur laoreet leo. Sed sodales quam tortor, at tincidunt mi tincidunt eget. Aliquam erat volutpat. Maecenas eget nibh ac lacus tempor lobortis vel non leo. Sed lobortis, augue non pretium lobortis, mauris est sodales diam, eu iaculis odio est a augue. Aliquam eu quam et quam lacinia vulputate placerat vel eros. Sed iaculis vulputate ante vitae pellentesque.\r\n\r\nClass aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Quisque tempus sapien quis accumsan porttitor. Mauris tempus, tellus vitae consequat laoreet, ipsum augue semper quam, eget lobortis sem leo eget diam. Nullam vel interdum dolor, eget condimentum ligula. In hac habitasse platea dictumst. Sed vel eros a nunc aliquet laoreet eget quis elit. Donec orci ante, egestas a ligula commodo, accumsan fringilla orci. Pellentesque in nibh a lorem interdum volutpat nec vel mauris. Donec ipsum massa, lobortis eu elit eu, vehicula ornare enim. Quisque vehicula massa vitae tellus elementum, ut fermentum nunc eleifend. Cras bibendum erat et nunc dapibus, a porta odio suscipit. Nullam pulvinar a nibh quis euismod. Integer dictum auctor blandit.\r\n\r\nVestibulum ultrices eleifend ultrices. Vivamus tincidunt turpis sed augue luctus cursus. Fusce non dolor metus. Fusce porta id justo non tristique. Integer sit amet odio tempor, imperdiet justo iaculis, aliquam nulla. Donec suscipit risus sit amet ex molestie dapibus. Curabitur tristique elit id nisi lacinia porttitor. Vivamus sollicitudin sollicitudin nisl eu dignissim. Pellentesque a aliquam nulla, eu malesuada dui. Morbi id lectus sed lacus convallis consectetur eu non metus. Vivamus id porta magna, sed eleifend magna. Donec mollis enim mi, vitae faucibus nisi molestie nec. Donec magna risus, viverra eget molestie eu, ultrices sit amet nibh. Cras egestas, felis lacinia tincidunt suscipit, justo magna ultrices enim, id tincidunt mi dolor vel purus. Sed fermentum blandit magna, sit amet euismod arcu scelerisque et. Vivamus at porta augue.');


CREATE TABLE `categories` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(45) CHARACTER SET utf8 NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;

INSERT INTO `categories` VALUES (1, 'Sci-fi');
INSERT INTO `categories` VALUES (2, 'History');
INSERT INTO `categories` VALUES (3, 'Educational');
INSERT INTO `categories` VALUES (4, 'Adventure');
INSERT INTO `categories` VALUES (5, 'Comedy');


CREATE TABLE `book_categories` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `book_id` int(10) unsigned NOT NULL,
  `category_id` int(11) unsigned NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;

INSERT INTO `book_categories` VALUES (1, 1, 3);
INSERT INTO `book_categories` VALUES (2, 1, 1);
INSERT INTO `book_categories` VALUES (3, 2, 3);
INSERT INTO `book_categories` VALUES (4, 3, 2);
INSERT INTO `book_categories` VALUES (5, 3, 3);
INSERT INTO `book_categories` VALUES (6, 4, 2);
INSERT INTO `book_categories` VALUES (7, 5, 4);
INSERT INTO `book_categories` VALUES (8, 5, 4);
INSERT INTO `book_categories` VALUES (9, 6, 4);